### ISSUE TITLE
throw Error

### ISSUE THREAD

**Issue by qwefgh90** [qwefgh90/JSearch#4]
https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiiqpvFsfzKAhXENJQKHfVdDOYQFgghMAA&url=http%3A%2F%2Fwww.smtech.go.kr%2Ffront%2Fcomn%2FAtchFileDownload.do%3Bjsessionid%3DDld9AB2Y80e56T0Ey5WavX1z8jO6JJCnwL4e14Lstn9WawSm62IUYC9cEjuVnGoN.smwas1_servlet_engine2%3FatchFileId%3DS00002490860&usg=AFQjCNEwi9LzrNp1Q5fBF9Neq6WT7E2rtA&sig2=ytPYro4QcOEyb6QxF9D7bQ

Exception in thread "Thread-6" java.lang.NoClassDefFoundError: com/argo/hwp/HwpTextExtractor
    at com.qwefgh90.io.jsearch.extractor.HwpTextExtractorWrapper.extract(HwpTextExtractorWrapper.java:31)
    at com.qwefgh90.io.jsearch.JSearch.extractContentsFromFile(JSearch.java:67)
    at io.github.qwefgh90.crawler.GCrawlerPostProcessor.run(GCrawlerPostProcessor.java:219)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.argo.hwp.HwpTextExtractor
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 4 more

**Comment by qwefgh90** [comment]
for solve this problem, I add java-hwp to maven shaded jar
